name: ChristmasEvent
version: '${project.version}'
main: indy.christmasevent.main.Main
api-version: 1.16
authors: [ indyPlayGames ]
depend: [Vault]

commands:
  christmasevent:
    description: Base plugin command.
    aliases: [ event ]

permissions:
  christmasevent.*:
    description: all permissions
    default: op
  christmasevent.start:
    description: permission to start event
    default: op
  christmasevent.stop:
    description: permission to stop event
    default: op
  christmasevent.spawn:
    description: permission to spawn elves
    default: op
  christmasevent.exchange:
    description: permission to exchange gifts
    default: true
  christmasevent.give:
    description: permission to give gifts
    default: op