name: ChristmasEvent
version: '${project.version}'
main: indy.christmasevent.main.Main
api-version: 1.16
authors: [ indyPlayGames ]
depend: [Vault]

commands:
  event:
    description: Base plugin command.
    aliases: [ event ]

permissions:
  christmasevent.*:
    description: all permissions
    default: op
  christmasevent.start:
    description: permission to start event
    default: op
  christmasevent.stop:
    description: permission to stop event
    default: op